### ISSUE TITLE
amend: Rollback amends that require --merge

### ISSUE THREAD

**Issue by bcongdon** [arxanas/git-branchless#202]
Followup to #170.

If an amend requires a `--merge` (e.g. the post-amend restack requires an merge), you can end up in an un-restacked state. The amend succeeds, and HEAD gets moved to the new commit, but the restack fails, so you end up in a halfway state.

For example:
```
$ git amend
...
This operation would cause a merge conflict:
• (2 conflicting files) 4f2b8f07 Something with a conflict
To resolve merge conflicts, retry this operation with the --merge option.

$ git sl
◯ 4c8285ee 12h feat(amend): Initial amend command
┣━┓
┃ ✕ 632a87e5 35m (rewritten as 03c75042) In-progress refactors
┃ ┃
┃ ◯ 4f2b8f07 22m Something with a conflict
┃
● 03c75042 6s (feat/amend-command) In-progress refactors
```

If an amend requires a merge, I'd prefer to stay on the original commit, and have `git branchless` prompt me to redo the amend with the `--merge` flag.

**Comment by bcongdon** [comment]
@arxanas Since amend performs its actions within the context of an event transaction, is there a simple way to "abort" a transaction? (Or would we have to invoke `undo` somehow?)

**Comment by arxanas** [comment]
Actually, I saw this as the desired behavior. It's kind of like the jj approach of allowing conflicts to exist and just having to resolve them later. I think we should just update the wording to suggest that you run `git restack --merge` instead of retrying the operation.

As a general note, there's not a way to abort a transaction; instead, it's best to just avoid committing the transaction until it's confirmed. Sometimes it's a bit difficult to orchestrate in concert with reference moves, see e.g. here:

https://github.com/arxanas/git-branchless/blob/708b76260e19a9dc5ab4fa910a0eb613fc8f077e/src/core/rewrite/execute.rs#L34-L39
