### ISSUE TITLE
Same name as pypi's git-branchless

### ISSUE THREAD

**Issue by fdenzer** [arxanas/git-branchless#58]
👀 https://github.com/krobelus/git-branchless/issues/1

They might rename their package, though. I was looking for this git branchless, but found the other one and an unusual git workflow-blogpost, perhaps using the other toolset, in my top google hits.

Update:
https://github.com/arxanas/git-branchless#related-work states that the other software is known you. Still, SEO-wise a different name might help.

**Comment by arxanas** [comment]
There's also some discussion starting at https://github.com/arxanas/git-branchless/discussions/45#discussioncomment-930092.

I'm open to a new name, but according to at least one user, the name is intuitive: https://github.com/arxanas/git-branchless/discussions/45#discussioncomment-930083, and I haven't been able to think of an equally-appropriate name. Actually, it's a little hard to motivate why a branchless workflow would be better (see #5, https://github.com/arxanas/git-branchless/issues/6#issuecomment-817082034).

I might "win" on the SEO front considering the greater amount of traffic directed to this project. But that being said, I think competition in the space is good, especially considering [Mr. Devault's usage of the other workflow](https://drewdevault.com/2020/04/06/My-weird-branchless-git-workflow.html) which you mention. (If I actually wanted to win, then I wouldn't have linked to the other project in the `README` 😅 .)

Somewhat amusely, although the other `git-branchless` project precedes this project, I published to PyPI and then migrated to Rust before the other project's first release to PyPI. Timeline:

* 2020-06-30: [initial commit to `krobelus/git-branchless`](https://github.com/krobelus/git-branchless/commit/67994b45544d23d1f13a15021266da5b1715f32e).
* 2020-11-17: [initial commit to `arxanas/git-branchless`](https://github.com/arxanas/git-branchless/commit/d0a1177a60f7cec9ef1e6f0e3dc845a002a09052).
* ca. 2020-12-10: [`arxanas/git-branchless` published to PyPI (under package `branchless`)](https://github.com/arxanas/git-branchless/commit/3df77a827f491b37f08446599b7dcea48c976380).
* 2021-01-20: [`krobelus/git-branchless` announced](https://discuss.kakoune.com/t/git-branchless-efficiently-manage-topic-branches-without-switching-branches/1545/18).
* 2021-03-15: [`arxanas/git-branchless` completes port to Rust](https://github.com/arxanas/git-branchless/commit/1719a7e393eb7fcd98533401eabdc982d03f1401) and [published to crates.io](https://crates.io/crates/git-branchless/0.2.0).
* after 2021-03-15: The `branchless` package is deleted from PyPI at some point after I discovered the other `git-branchless` project, in order to reduce confusion. The situation could have been even more confusing than it is now!
* 2021-04-21: [`krobelus/git-branchless` published to PyPI (under package `git-branchless`)](https://pypi.org/project/git-branchless/0.0.5/#history).

**Comment by krobelus** [comment]
Hi, thanks for your thoughtful comment. I plan to rename mine but I don't know when I'll get to it.
