### ISSUE TITLE
In the demo, do the same tasks with and without `git-branchless`

### ISSUE THREAD

**Issue by dfabulich** [arxanas/git-branchless#6]
I watched your demo, and it mostly just showed you doing a daily workflow. It seemed fine, but I couldn't see how it was better than what I do now. (Except for `git undo`, which is pretty cool, and I think could stand to be separated out as its own feature.)

I'd like to see the demo compare and contrast doing daily tasks with and without `git-branchless`, to show how much better `git-branchless` is.

**Comment by arxanas** [comment]
@dfabulich Thanks, you're right. I think it would be best to split up the demo into multiple demos showcasing specific tasks and how they can be accomplished with and without `git-branchless`, rather than attempting one uber-demo. It might also be nice to have a side-by-side demo, (hopefully) showing that the same task is faster in `git-branchless` in real-time.

Unfortunately, the `git undo` feature doesn't stand alone, because it requires the event log which is managed by the `git-branchless` hooks. You could install `git-branchless` just for the `git undo` feature and ignore the rest of the features, though.

I appreciate your feedback!

**Comment by arxanas** [comment]
@dfabulich I tried a demo for amending a parent in a complicated history. Do you think this is a more compelling example of a demo?

Without git-branchless:

[![asciicast](https://asciinema.org/a/fVKJ9tVbFWTzt5VhY3s2fKjsa.svg)](https://asciinema.org/a/fVKJ9tVbFWTzt5VhY3s2fKjsa)

With git-branchless:

[![asciicast](https://asciinema.org/a/emLGsHFSq9rfOZnRIlakqBW7i.svg)](https://asciinema.org/a/emLGsHFSq9rfOZnRIlakqBW7i)

**Comment by dfabulich** [comment]
I *very* dimly see what you're getting at here. Your "without" example is quite confusing. You're "recovering from an upstream rebase" in the terms defined in https://git-scm.com/docs/git-rebase but in an extremely non-standard workflow, because the `bar` branch isn't "upstream" of `baz`. You didn't even get as far as forcing `bar` back into `master`; instead you're rebasing `baz` onto `bar~1`, which seems weird and contrived.

But I think what you meant to say is: "yeah, but suppose I _had_ force-pushed `bar` to `master`. _Then_ what would `baz` do?" And the answer from the documentation is something like `git rebase --onto master master@{1}`, but for one thing you'd have to _know_ that you needed to recover from an upstream rebase, and for another you'd have to somehow figure out that `master@{1}` was what you needed. This is a real problem with git rebases, and a solution for _that_ problem would be quite welcome.

But I don't think `branchless` would help even in this case. The `bar` developer would have done all of that work on a separate machine; the `bar` developer's `branchless` DB wouldn't be accessible to the `baz` developer. So even `branchless` couldn't help in the real case.

But overall this tells me that your feature list is still missing. I now think your feature list is something like:

* Git rebase without fear: Git `rebase` lets you rewrite history with ease, but it forces your teammates to take manual action to "recover" from upstream rebases. `git-branchless` allows any branch to recover from arbitrary upstream rebases automatically, without annoying your teammates.
* Undo anything with ease: `git-branchless` lets you undo stuff that's difficult to undo in stock Git, like undoing rebases, undoing hard resets, and undoing rebase recovery
* Visualize rewritten history: View a graph of rewritten commits, viewing not just the current history, but the history of your history in an easy-to-read ASCII chart

But even there, I'm not sure if this is accurate. (I don't think the rebase feature actually works across teammates.)

**Comment by arxanas** [comment]
It's not meant to recover from upstream rebases (where "upstream" means "someone else's repo"). It won't work across teammates, like you say, since the database is not shared.

It's meant to handle the case of a single user backtracking on their history. For example, if you had two ideas to solve a problem, and you weren't sure which worked, but they both had some common work, then you base both approaches on top of the common work:

```
◇ 4815ad42 35d (master) Initial commit                                        
┃                                                                             
◯ d360792b 28s Some base work (which has a bug)
┣━┓                                                                           
┃ ◯ b68a339f 19s Approach 1 to solve the problem
┃                                                                             
● ec642591 17s Approach 2 to solve the problem
```

At a later time, you want to fix the base commit, and make sure that all the dependent work is up-to-date, so you do the thing in the demo, where you rewrite the shared parent commit and `restack` all of the dependent commits. Does that make sense?

In your typical workflow, what would you do you if you wanted to try out two approaches, but share some code between them? Would you create a first branch the base work and the first approach, and then create a second branch based off of only the base work? Or just fold the shared work into both commits individually? Or use `git stash` to set aside one approach while you work on the other one?

At work, I currently have a tree like the above. There's a bug-fix to the base code generation system, and then I have two approaches for hooking together a certain thing into the code generation system. They are relatively different approaches, but I want to make sure I can examine the other approach, and that the other approach isn't lost if I decide to return to it.

**Comment by dfabulich** [comment]
Let me try this, then:

1. Undo anything with ease: `git-branchless` lets you undo stuff that's difficult to undo in stock Git, like undoing rebases, undoing hard resets, and undoing rebase recovery
2. Visualize rewritten history: View a graph of rewritten commits in an easy-to-read ASCII chart, showing not just the current history, but the history of your history
3. Rebase without fear: Git `rebase` lets you rewrite history with ease, but if your local history has a few branches with a few experimental approaches, when it comes time to rebase them into a linear timeline, you'll be forced to carefully "recover" from your own rebases. `git-branchless` allows any local commit to recover from arbitrary local rebases automatically and flawlessly, giving you the confidence to craft a perfect pull request.

I think you perceive feature 3 to be the primary value of `git-branchless`, but IMO the value of that feature is really low. I do my fair share of local experiments, and I even do local rebases, and I have encountered issues with local rebase recovery, but in the very worst case, it's just a handful of commits; I just manually cherry-pick a few times, and it's fine. (And, as you point out, many users don't even think you ought to rebase locally!)

**Comment by arxanas** [comment]
Closing due to #11. The project is no longer marketed as directly improving specific tasks already in your workflow, but adding tools for extensive history editing.
