### ISSUE TITLE
List of Commands?

### ISSUE THREAD

**Issue by AriaFallah** [arxanas/git-branchless#88]
Hey! Love the idea for this project. I'm completely new to it, and I can't really find a list of commands (+flags they can take) anywhere in the docs. Is there something like that?

If not, is there somewhere in the source code I could just read in the meantime? For example, I'd love to learn if `git sl` takes a flag that can show more history than just the past few commits or if there's a flag to put the most recent commit at the top instead of at the bottom.

**Comment by arxanas** [comment]
@AriaFallah Thanks again for your feedback. I've started work on a command overview  in the [Wiki](https://github.com/arxanas/git-branchless/wiki). Please check the articles in the sidebar and let me know if you have any feedback. For example, here's the documentation on `git move`: https://github.com/arxanas/git-branchless/wiki/Command:-git-move

I've also opened #112 to attempt to fix the usage of `--help` under Git for at least some cases.

**Comment by AriaFallah** [comment]
I love it. Thanks a lot :)

**Comment by martinvonz** [comment]
Agreed, great documentation!

A bit off topic, but I have a comment about what to do about the `git move -s 87b20a4b -d xyzzy` at the end (instead of erroring out because it's a cycle). Another reasonable behavior would be to leave the commits in the range between those commits in place but move any side branches on top of the destination. You could then do something like `git move -s <old origin/main> -d <new origin/main>` to rebase all the commits you had off of `<old origin/main>`.

**Comment by arxanas** [comment]
@martinvonz That's a good idea. It's also currently the case that `git move` without any parameters fails because it takes on the default behavior of attempting to rebase the current commit on top of itself, which would form a cycle. Adopting your suggestion would cleanly make it a no-op.
